# Generated by Django 4.2.5 on 2025-03-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_tool', '0002_extendedagkategorie_studentsessionbuffer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsessionbuffer',
            name='ag',
        ),
    ]
