[metadata]
name = moto-analysis-tool
version = 0.1.0
description = An modulare Extension for the MOTO-App, providing analysis tools and visualisation 
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/christiank119/MOTO-BA
author = Christian Kamann
author_email = christian.kamann@uni-muenster.de
license = AGPL-3.0-only
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Framework :: Django :: 4.2
    Intended Audience :: Developers
    License :: OSI Approved :: GNU Affero General Public License v3
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Framework :: Django :: 4.2
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
include_package_data = true
packages = find:
python_requires = >=3.8
install_requires =
    Django>=4.2.0
    pandas>=1.5.0
    numpy>=1.21.0
    scikit-learn>=1.0.0
    mlxtend>=0.21.0

[options.packages.find]
exclude =
    tests

[options.package_data]
analysis_tool =
    static/css/heatmap/*.css
    templates/heatmap/*.html
    templates/*/*.html