# Generated by Django 4.2.5 on 2025-03-12 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_raum_color_raum_kategorie_alter_raum_geschoss_and_more'),
        ('analysis_tool', '0004_studentsessionbuffer_ag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='raumplaene/')),
                ('width', models.PositiveIntegerField(help_text='Breite des Bildes in Pixel')),
                ('height', models.PositiveIntegerField(help_text='Höhe des Bildes in Pixel')),
            ],
        ),
        migrations.CreateModel(
            name='RaumPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.JSONField(help_text="Liste von Koordinaten z. B. [{'x': 10, 'y': 20}, ...]")),
                ('raum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.raum')),
                ('raumplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_tool.raumplan')),
            ],
        ),
    ]
