# Generated by Django 4.2.5 on 2025-03-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0002_raum_color_raum_kategorie_alter_raum_geschoss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_name', models.CharField(max_length=50)),
                ('max_anzahl', models.PositiveIntegerField()),
                ('total_available_time', models.FloatField(help_text='Verfügbare Zeit in Stunden (Kapazität * AG-Dauer)')),
                ('actual_usage_time', models.FloatField(help_text='Summe der tatsächlichen Anwesenheitszeit aller Schüler in Stunden')),
                ('utilization_percentage', models.FloatField(help_text='Auslastung in Prozent')),
                ('peak_participants', models.PositiveIntegerField(default=0, help_text='Maximal gleichzeitig teilnehmende Schüler')),
                ('fully_utilized_percentage', models.FloatField(help_text='Prozentualer Anteil der AG-Zeit, in der sie voll ausgelastet war')),
                ('zeitraum_start', models.DateTimeField()),
                ('zeitraum_end', models.DateTimeField()),
                ('ag_kategorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.agkategorie')),
                ('raum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.raum')),
            ],
        ),
    ]
