# Generated by Django 4.2.5 on 2025-03-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_raum_color_raum_kategorie_alter_raum_geschoss_and_more'),
        ('analysis_tool', '0003_remove_studentsessionbuffer_ag'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsessionbuffer',
            name='ag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.ag'),
        ),
    ]
