# Generated by Django 4.2.5 on 2025-03-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_raum_color_raum_kategorie_alter_raum_geschoss_and_more'),
        ('analysis_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedAGKategorie',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.agkategorie',),
        ),
        migrations.CreateModel(
            name='StudentSessionBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
                ('duration', models.FloatField(help_text='Dauer in Stunden')),
                ('is_offered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.ag')),
                ('ag_kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.agkategorie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schueler')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOverallAnalysis',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.schueler')),
                ('total_ogs_time', models.FloatField(default=0.0, help_text='Gesamte OGS-Zeit in Stunden (von der ersten Anmeldung bis zur letzten Abmeldung pro Tag aufsummiert)')),
                ('avg_ag_per_day', models.FloatField(default=0.0, help_text='Durchschnittliche Anzahl der AG-Besuche pro Tag')),
                ('avg_continuous_ag_duration', models.FloatField(default=0.0, help_text='Durchschnittliche Dauer zusammenhängender AG-Besuche in Stunden (über alle AGs)')),
                ('avg_continuous_ag_kategorie_duration', models.FloatField(default=0.0, help_text='Durchschnittliche Dauer eines kontinuierlichen Besuchs pro AGKategorie in Stunden')),
                ('offered_ag_time_percentage', models.FloatField(default=0.0, help_text='Prozentsatz der insgesamt in AGs verbrachten Zeit, die in angebotenen Sessions lag')),
                ('favourite_time', models.FloatField(default=0.0, help_text='Zeit in Stunden, die in der Lieblings-AGKategorie verbracht wurde')),
                ('favourite_frequency', models.PositiveIntegerField(default=0, help_text='Anzahl der Besuche in der Lieblings-AGKategorie')),
                ('favourite_time_percentage', models.FloatField(default=0.0, help_text='Prozentsatz der Gesamt-OGS-Zeit, die in der Lieblings-AGKategorie verbracht wurde')),
                ('favourite_ag_kategorie', models.ForeignKey(blank=True, help_text='Die AGKategorie, in der der Schüler insgesamt die meiste Zeit verbracht hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.agkategorie')),
                ('frequent_ag', models.ForeignKey(blank=True, help_text='Die AG, die der Schüler am häufigsten besucht hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.ag')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAGCategoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.FloatField(default=0.0, help_text='Gesamte Zeit in Stunden, die der Schüler in dieser AGKategorie verbracht hat')),
                ('frequency', models.PositiveIntegerField(default=0, help_text='Anzahl der Besuche (Sitzungen) in dieser AGKategorie')),
                ('average_session_duration', models.FloatField(default=0.0, help_text='Durchschnittliche Dauer eines zusammenhängenden Besuchs in Stunden')),
                ('offered_ag_time_percentage', models.FloatField(default=0.0, help_text='Prozentsatz der in AGs dieser Kategorie verbrachten Zeit, bei denen ein Angebot vorlag')),
                ('ag_kategorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.agkategorie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schueler')),
            ],
            options={
                'unique_together': {('student', 'ag_kategorie')},
            },
        ),
    ]
